import type { Song } from '../../_types/types';

export const exampleSongs: Song[] = [
	{
		id: 1,
		imageUrl: '/exampleImage.webp',
		title: 'Neon Heartbeat',
		writer: 'Zoe Chen',
		genre: 'Synth-pop',
		duration: 198,
		slug: `neon-heartbeat`,
		price: 89900,
	},
	{
		id: 2,
		imageUrl: '/exampleImage.webp',
		title: 'Midnight Carousel',
		writer: 'Jamal Thompson',
		genre: 'Disco',
		duration: 215,
		slug: `midnight-carousel`,
		price: 75000,
	},
	{
		id: 3,
		imageUrl: '/exampleImage.webp',
		title: 'Whisper in the Wind',
		writer: 'Olivia Nakamura',
		genre: 'Adult Contemporary',
		duration: 237,
		slug: `whisper-in-the-wind`,
		price: 120000,
	},
	{
		id: 4,
		imageUrl: '/exampleImage.webp',
		title: 'Electric Dreams',
		writer: 'Alex Novak',
		genre: 'House',
		duration: 189,
		slug: `electric-dreams`,
		price: 95000,
	},
	{
		id: 5,
		imageUrl: '/exampleImage.webp',
		title: 'Crystal Skies',
		writer: 'Fatima Al-Hassan',
		genre: 'Dream Pop',
		slug: `crystal-skies`,
		price: 135000,
		duration: 204,
	},
	{
		id: 6,
		imageUrl: '/exampleImage.webp',
		title: 'Urban Rhythm',
		writer: 'DeShawn Williams',
		genre: 'Hip-hop',
		duration: 183,
		slug: `urban-rhythm`,
		price: 110000,
	},
	{
		id: 7,
		imageUrl: '/exampleImage.webp',
		title: 'Starlight Serenade',
		writer: `Emma O'Brien`,
		genre: 'Indie Pop',
		duration: 226,
		slug: `starlight-serenade`,
		price: 85000,
	},
	{
		id: 8,
		imageUrl: '/exampleImage.webp',
		title: 'Neon Nights',
		writer: 'Raj Patel',
		genre: 'Synthwave',
		duration: 195,
		slug: `neon-nights`,
		price: 99000,
	},
	{
		id: 9,
		imageUrl: '/exampleImage.webp',
		title: 'Velvet Thunder',
		writer: 'Lena Schmidt',
		genre: 'Electro-pop',
		duration: 210,
		slug: `velvet-thunder`,
		price: 145000,
	},
	{
		id: 10,
		imageUrl: '/exampleImage.webp',
		title: 'Sunburst',
		writer: 'Carlos Mendoza',
		genre: 'Tropical House',
		duration: 187,
		slug: `sunburst`,
		price: 79000,
	},
	{
		id: 11,
		imageUrl: '/exampleImage.webp',
		title: 'Echoes of You',
		writer: 'Aisha Johnson',
		genre: 'R&B',
		duration: 231,
		slug: `echoes-of-you`,
		price: 125000,
	},
	{
		id: 12,
		imageUrl: '/exampleImage.webp',
		title: 'Cybernetic Love',
		writer: 'Yuki Tanaka',
		genre: 'Futurepop',
		duration: 193,
		slug: `cybernetic-love`,
		price: 105000,
	},
];
